# STAT163 · pandas and notebook basics — a first session

For you if notebooks are new to you, if you have never used pandas, or if your last
contact with Python was a year ago. About **45 minutes**. Then continue with
`01-dataframes-and-profiling.ipynb`.

Part 1 is about the notebook itself. Parts 2 to 7 follow the order of the video
[*Pandas basics*](https://www.youtube.com/watch?v=6th7928WKII) by Matvii Strechen, 25 minutes. Watch it and run the matching
part here, or run this notebook on its own.

**How to use it.** Run the cells one at a time, from top to bottom. Three kinds of cells:

- **Read and run.** Run the cell and read the output. Most cells are this kind.
- **Predict.** Before you run the cell, write what you expect in the comment line.
  Then run it and compare. The answer sits under **Answer** below the cell; open it
  after you run.
- **Try it.** Change one thing in the code and run it again.

Four cells stop with an error on purpose, and one prints a warning and carries on.

Nothing here is submitted or graded. AI is welcome. Ask it to explain a cell, or to
explain why your prediction was wrong.

## 1. How a notebook works

A notebook is a list of cells. A cell holds either text, like this one, or code, like
the next one. You run a code cell with **Shift+Enter**: the code runs, its result
appears under the cell, and the cursor moves to the next cell.

In [1]:
1 + 1

2

A code cell shows something under it when it runs. Which values?

In [2]:
# Predict: what appears under this cell — 10, 15, or both?
x = 5
x * 2
x * 3
#15

15

<details>
<summary>Answer</summary>

A code cell shows the value of its **last line** and nothing else. Only 15. `x = 5` is an assignment and has no value to show, `x * 2` is not the last
line, and `x * 3` is.

</details>

To show more than one thing, use `print`:

In [3]:
print(x * 2)
print(x * 3)

10
15

### Cells share one memory

Every cell runs in the same Python session, called the **kernel**. A variable made in
one cell exists for every cell you run afterwards, wherever that cell sits on the page.
The number in brackets on the left of a code cell says when it ran.

In [3]:
y = x + 1
y

6

**Try it.** Insert a new code cell **above the cell that made `y`**. In Jupyter: click
that cell, press Esc, then A. In Colab: move the mouse to the top edge of that cell and
click **+ Code**. Type `y` in the new cell and run it. It shows 6, although the cell that
made `y` is below it. The order in which cells **ran** is what counts, not their order on the
page.

A notebook that works when you run its cells in a strange order
can fail when somebody else runs it top to bottom. Before you submit a notebook, restart
and run everything: in Jupyter **Kernel → Restart Kernel and Run All Cells**, in Colab
**Runtime → Restart session and run all**. A restart empties the memory. The text, the
code and the saved outputs stay in the file. The variables do not.

In [4]:
# Predict: no cell has made a variable called z. What happens?
print(z)

NameError: name 'z' is not defined

<details>
<summary>Answer</summary>

A `NameError`. Read the last line of a red block first: it names the error and says what
went wrong. You see this same error when you run a cell before the cell that makes its
variable, and after a restart.

</details>

**Save** with Ctrl+S or Cmd+S; in Colab use **File → Save a copy in Drive** first, or
your edits vanish with the tab.

## 2. A Series is a list of values with a label on each one

pandas is imported under the short name `pd`.

In [5]:
import pandas as pd

print(pd.__version__)

3.0.5

In [6]:
a = pd.Series([1, 2, 3, 10, 3, 7])
a

0     1
1     2
2     3
3    10
4     3
5     7
dtype: int64

The left column is the **index**: one label per value. When you do not give labels,
pandas numbers the values from 0. The last line names the type of the values.

You can give your own labels:

In [7]:
a = pd.Series([1, 2, 3, 10, 3, 7], index=["a", "b", "c", "d", "e", "f"])
a

a     1
b     2
c     3
d    10
e     3
f     7
dtype: int64

Now a Series works like a dictionary: a label finds a value.

In [8]:
a["d"]

np.int64(10)

### pandas and NumPy

The value came back as `np.int64(10)`, not as `10`. `np` is NumPy, a library for arrays
of numbers. pandas does not store numbers itself: it reuses NumPy's objects and types, the
way one library can build on another's work. `int64` is NumPy's type for a whole number
kept in a 64-bit slot.

Python's own `1` and NumPy's `np.int64(1)` are both the number one, and they compare
equal. A Python `int` is a separate object that can grow as large as memory allows. A
NumPy `int64` is one fixed-size slot in a block where every value has the same type,
which is what lets a whole column be processed in one call. In your code the two mix
freely, and `print` shows the bare number for either.

In [9]:
value = a["d"]
print(value == 10)
print(type(value))
print(type(10))

True
<class 'numpy.int64'>
<class 'int'>

In [10]:
# Predict: what happens when there are three values and two labels?
pd.Series([1, 2, 3], index=["a", "b"])

ValueError: Length of values (3) does not match length of index (2)

<details>
<summary>Answer</summary>

A `ValueError`. The index must have exactly one label per value.

</details>

## 3. Arithmetic works label by label

Make a second Series with some labels in common with `a` and some new ones:

In [19]:
b = pd.Series([1, 5, 2, 4], index=["a", "c", "g", "x"])
b

a    1
c    5
g    2
x    4
dtype: int64

In [20]:
# Predict: how many values will the result have, and which ones will be numbers?
a + b

a    2.0
b    NaN
c    8.0
d    NaN
e    NaN
f    NaN
g    NaN
x    NaN
dtype: float64

<details>
<summary>Answer</summary>

Eight values, and only two of them are numbers. pandas adds label by label: `a` at label
`a` plus `b` at label `a` gives 2, and the same for `c`. Where a label exists on one side
only, there is nothing to add, so the result is `NaN`.

</details>

`NaN` stands for "not a number" and is how pandas marks a missing value.

This matching by label is called **alignment**. It happens in every operation between
two Series. Arithmetic with a single number needs no matching:

In [21]:
a + 7

a     8
b     9
c    10
d    17
e    10
f    14
dtype: int64

In [13]:
a * 2

a     2
b     4
c     6
d    20
e     6
f    14
dtype: int64

### pandas against plain Python

The same `+` means something else on a Python list. Two lists are joined end to end:

In [14]:
[1, 2, 3] + [10, 20]

[1, 2, 3, 10, 20]

A list plus a number is an error, because Python does not know whether you mean every
element. pandas defines both: `+` between two Series adds label by label, and `+` with a
number adds it to every value.

**Try it.** In the cell below, change one label in `b2` to `"d"` and run it. How many
numbers now?

In [15]:
# Try it
b2 = pd.Series([1, 5, 2, 4], index=["a", "c", "d", "x"])
a + b2

a     2.0
b     NaN
c     8.0
d    12.0
e     NaN
f     NaN
x     NaN
dtype: float64

## 4. A DataFrame is a set of Series that share one index

Put two Series side by side and you get a table. Each Series becomes a column, and the
labels line up:

In [22]:
df = pd.DataFrame({"A": a, "B": b})
df

      A    B
a   1.0  1.0
b   2.0  NaN
c   3.0  5.0
d  10.0  NaN
e   3.0  NaN
f   7.0  NaN
g   NaN  2.0
x   NaN  4.0

Where a column has no value for a label, the value is `NaN`.

A column name in square brackets pulls one column back out as a Series, the way a key
pulls a value out of a Python dictionary:

In [19]:
df["A"]

a     1.0
b     2.0
c     3.0
d    10.0
e     3.0
f     7.0
g     NaN
x     NaN
Name: A, dtype: float64

In [16]:
# Predict: what happens?
df["C"]

NameError: name 'df' is not defined

<details>
<summary>Answer</summary>

A `KeyError`: there is no column called `C`.

</details>

Arithmetic with a number applies to every value:

In [23]:
df * 2

      A     B
a   2.0   2.0
b   4.0   NaN
c   6.0  10.0
d  20.0   NaN
e   6.0   NaN
f  14.0   NaN
g   NaN   4.0
x   NaN   8.0

## 5. A table from a file

The table is one month of sales from an online shop, 78 015 rows. One row is one line on one receipt: one product,
bought once. `Invoice` is the receipt number, `StockCode` the product code,
`Description` the product name, `Quantity` how many, `InvoiceDate` when, `Price` per
unit, `Customer ID` who bought, `Country` where it was shipped.

The table is read straight from the web.

In [27]:
url = "https://raw.githubusercontent.com/stat163-2026t1/week2-pre-lecture/main/data/online_retail_2010_11.csv"
df = pd.read_csv(url)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,529995,48184,DOORMAT ENGLISH ROSE,6,2010-11-01 08:56:00,7.95,16316.0,United Kingdom
1,529995,48187,DOORMAT NEW ENGLAND,4,2010-11-01 08:56:00,7.95,16316.0,United Kingdom
2,529995,21523,DOORMAT FANCY FONT HOME SWEET HOME,10,2010-11-01 08:56:00,6.75,16316.0,United Kingdom
3,529995,22708,WRAP DOLLY GIRL,25,2010-11-01 08:56:00,0.42,16316.0,United Kingdom
4,529995,22781,GUMBALL MAGAZINE RACK,4,2010-11-01 08:56:00,7.65,16316.0,United Kingdom

/`head()` shows the first five rows. `shape` gives (rows, columns), and `columns` lists
the column names, which you will need to spell exactly. Type `df.` and press **Tab** to
see everything a table can do.

There are two ways to reach a column: `df["Quantity"]` and `df.Quantity`. Only the first
works for every name. A name with a space or a dash, such as `Customer ID`, or a name
pandas already uses for a method, such as `count`, cannot follow the dot. This course
uses brackets.

In [28]:
df.shape

(78015, 8)

In [29]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [30]:
df["Quantity"]

0         6
1         4
2        10
3        25
4         4
         ..
78010    12
78011     2
78012    12
78013    24
78014    10
Name: Quantity, Length: 78015, dtype: int64

A column is a Series, so everything from parts 2 and 3 applies to it. Two questions a
column can answer:

In [31]:
print(df["Quantity"].max())
print(df["Quantity"].mean())

9360
8.637518425943728

### Why pandas, and not a loop

You could compute the same things with a Python loop. Here is quantity times price for
each line, both ways. `%%time` at the top of a cell reports how long the cell
took.

In [32]:
%%time
revenue = []
for i in range(len(df)):
    revenue.append(df["Quantity"].iloc[i] * df["Price"].iloc[i])

CPU times: total: 4.44 s
Wall time: 5.37 s

In [33]:
%%time
revenue = df["Quantity"] * df["Price"]

CPU times: total: 0 ns
Wall time: 3.26 ms

The gap grows with the table. The reason is how the values are stored. In plain Python every number is a separate object with its own
type attached, and a loop handles them one at a time: read the type, do the arithmetic,
make a new object, and repeat 78 015 times. A Series keeps its values in one block of
memory with one type for the whole column, and an operation on it runs once, in compiled
code written in C, over the whole block. That is also why a column has exactly one
storage type: one type per block.

## 6. A condition gives a boolean mask

Compare a column with a number and you get a new Series, one `True` or `False` per row,
with the same labels. The comparison you write is the **condition**; the Series it
produces is the **boolean mask**, or mask for short. The picture: a mask lies over the
table and lets a row through where it is `True`.

In [29]:
df["Quantity"] > 20

0        False
1        False
2        False
3         True
4        False
         ...
78010    False
78011    False
78012    False
78013     True
78014    False
Name: Quantity, Length: 78015, dtype: bool

In plain Python, `5 > 20` gives one answer, and a list compared with a number is an
error. pandas defines the comparison per value, so one line asks the question of every
row at once.

In [34]:
# Predict: what does this number count?
(df["Quantity"] > 20).sum()

np.int64(7272)

<details>
<summary>Answer</summary>

`True` counts as 1 and `False` as 0, so the sum of a mask is the number of rows where
the condition holds. This is the usual way to count things in pandas.

</details>

Put the mask inside `df[...]` and you keep only the rows where it is `True`:

In [31]:
df[df["Quantity"] > 20]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
3,529995,22708,WRAP DOLLY GIRL,25,2010-11-01 08:56:00,0.42,16316.0,United Kingdom
7,529995,22052,VINTAGE CARAVAN GIFT WRAP,25,2010-11-01 08:56:00,0.42,16316.0,United Kingdom
8,529995,22719,GUMBALL MONOCHROME COAT RACK,24,2010-11-01 08:56:00,1.25,16316.0,United Kingdom
11,529995,22959,WRAP CHRISTMAS VILLAGE,25,2010-11-01 08:56:00,0.42,16316.0,United Kingdom
35,529997,22959,WRAP CHRISTMAS VILLAGE,25,2010-11-01 08:58:00,0.42,15312.0,United Kingdom
...,...,...,...,...,...,...,...,...
77988,536363,22665,RECIPE BOX BLUE SKETCHBOOK DESIGN,24,2010-11-30 19:27:00,2.55,13093.0,United Kingdom
77993,536363,22418,10 COLOUR SPACEBOY PEN,48,2010-11-30 19:27:00,0.85,13093.0,United Kingdom
77994,536363,21733,RED HANGING HEART T-LIGHT HOLDER,32,2010-11-30 19:27:00,2.55,13093.0,United Kingdom
77997,536363,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,64,2010-11-30 19:27:00,2.55,13093.0,United Kingdom
78013,536364,21181,PLEASE ONE PERSON METAL SIGN,24,2010-11-30 19:35:00,2.10,14441.0,United Kingdom

Look at the index on the left. The labels jump: 3, 7, 8, 11. Each row kept the label it
had in the full table. Filtering removes rows and changes nothing else.

So square brackets mean two things. A column **name** inside them gives a column. A
**mask** inside them gives rows.

### Combining conditions

In a loop you would write `and`, one row at a time:

In [35]:
matches = 0
for q in df["Quantity"]:
    if q >= 19 and q <= 25:
        matches = matches + 1
matches

4186

On whole columns `and` does not work. Python's `and` needs one `True` or `False` to
decide, and a mask holds 78 015 of them, one per row, so Python stops with an error
about the truth value of a Series being ambiguous. pandas gives three operators that
work value by value instead: `&` means and, `|` means or, `~` means not. Every condition
goes in its own parentheses, because Python does `&` before `>=`, the opposite of the
order it uses for `and`.

In [36]:
between = df[(df["Quantity"] >= 19) & (df["Quantity"] <= 25)]
between.shape

(4186, 8)

In [37]:
# Predict: what happens without the parentheses?
df[df["Quantity"] >= 19 & df["Quantity"] <= 25]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

<details>
<summary>Answer</summary>

A `ValueError` with a long message about "the truth value of a Series", the same error
that `and` gives. Python reads `&` before `>=`, so it tries to combine the number 19 with
the column first, and the rest fails.

</details>

The same rows, written the other way round: keep everything that is **not** below 19
**or** above 25.

In [38]:
outside = (df["Quantity"] < 19) | (df["Quantity"] > 25)
df[~outside].shape

(4186, 8)

The two shapes are equal, because the two masks pick the same rows.

You can also filter in two steps:

In [40]:
step1 = df[df["Quantity"] >= 19]

# Predict: is the shape the same as `between`? Look closely at the second line.
step2 = step1[step1["Quantity"] <= 25]
step2.shape

(4186, 8)

<details>
<summary>Answer</summary>

The same count, and a warning. The second line filters `step1` with a mask computed
on `df`. The two have different rows, so pandas lined them up by label before filtering,
which is alignment again, and then warned that it had to. Here that gives the right
answer. With labels that do not match, it gives a wrong one without any warning you would
notice. Compute the mask on the table you filter: `step1[step1["Quantity"] <= 25]`.

</details>

**Try it.** Count the rows shipped to France with a quantity above 50. You need a
condition on `Country`, a condition on `Quantity`, `&` between them, and `.sum()` at
the end.

In [44]:
import numpy as np
df.columns
df["Quantity"] = np.int64(df["Quantity"])
len(df[(df["Country"]=="France")&(df["Quantity"]>50)])# Try it

15

## 7. Picking by label and by position

Two ways to point at one row or one value:

- `.loc[label]` uses the **label** from the index.
- `.iloc[position]` uses the **position**, counting from 0, whatever the label says.

A Python list knows only positions, `items[0]`. A dictionary knows only keys, `d["a"]`.
A Series is both at once, so it needs two doors. On the small Series from part 2:

In [45]:
a

a     1
b     2
c     3
d    10
e     3
f     7
dtype: int64

In [46]:
print(a.loc["e"])
print(a.iloc[3])

3
10

Remove one value and see which of the two changes:

In [47]:
a2 = a.drop("d")
a2

a    1
b    2
c    3
e    3
f    7
dtype: int64

`drop` gave back a new Series and left `a` unchanged. Almost every pandas method works
this way: it returns a new object and touches nothing. To keep a result, assign it to a
name.

In [48]:
# Predict: which of the two answers changes, compared with the cell above?
print(a2.loc["e"])
print(a2.iloc[3])

3
3

<details>
<summary>Answer</summary>

`.loc["e"]` still gives 3: the label `e` still points at the same value. `.iloc[3]` now
gives 3 too, but for a different reason: the value 10 is gone, so the fourth position
holds what used to be the fifth. A label follows its value. A position counts places.

</details>

On the big table the labels are numbers, so the two look alike until rows are removed
or reordered:

In [49]:
df.loc[102]

Invoice                                   530001
StockCode                                  22665
Description    RECIPE BOX BLUE SKETCHBOOK DESIGN
Quantity                                       2
InvoiceDate                  2010-11-01 09:13:00
Price                                       5.91
Customer ID                                  NaN
Country                           United Kingdom
Name: 102, dtype: object

In [50]:
df.iloc[1]

Invoice                     529995
StockCode                    48187
Description    DOORMAT NEW ENGLAND
Quantity                         4
InvoiceDate    2010-11-01 08:56:00
Price                         7.95
Customer ID                16316.0
Country             United Kingdom
Name: 1, dtype: object

### Ranges

Both accept a range with a colon.

In [51]:
# Predict: how many values does each line return?
print(len(a.loc["c":"f"]))
print(len(a.iloc[1:3]))

4
2

<details>
<summary>Answer</summary>

`.loc` **includes** the end label. `.iloc` **excludes** the end position, like a Python
list. `"c":"f"` takes `c`, `d`, `e`, `f`. `1:3` takes positions 1 and 2.

</details>

`.loc` with a range follows the order the values are in right now. Sort the Series and
the same range gives a different answer:

In [52]:
b_sorted = b.sort_values()
b_sorted

a    1
g    2
x    4
c    5
dtype: int64

In [ ]:
# Predict: how many values? Look at where "c" and "g" are now.
b_sorted.loc["c":"g"]

<details>
<summary>Answer</summary>

Nothing: an empty Series. After sorting, `g` comes before `c`, and a range does not run backwards. The same
line on the unsorted `b` gives two values, `c` and `g`. A label range depends on the current order
of the rows, so use it only when you know that order.

</details>

## Summary

- Cells share one memory. The order you ran them in is what counts. Restart and run
  everything before you submit a notebook.
- A Series is values with labels. A DataFrame is Series side by side, sharing one index.
- Arithmetic between two Series matches labels. A label present on one side only gives
  `NaN`.
- `df["name"]` gives a column. `df[mask]` gives rows. A condition produces a boolean
  mask, a Series of True and False, and its `.sum()` is a count.
- Every condition in parentheses. `&` and, `|` or, `~` not.
- `.loc` picks by label and includes the end of a range. `.iloc` picks by position and
  excludes it.

Next: `01-dataframes-and-profiling.ipynb`, in this repository.